remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Modularity Project
description: Home for resources on modularity, work by <a href="https://www.annenbergpublicpolicycenter.org/annenberg-public-policy-center-distinguished-research-fellows/">Distinguished Research Fellows</a> Susan Ness and Chris Riley with the <a href="https://www.annenbergpublicpolicycenter.org/">Annenberg Public Policy Center</a> of the University of Pennsylvania.
